const CHURCHES=["Central","Cachoeira da Serra","Jardim Vitória","Jardim Planalto","PDS Brasília","Vila Isol","Terra Nossa","Pedra Alta"];
const AREAS={"Identidade":"#ff0046","Liderança":"#00bddd","Novas Gerações":"#ffb800","Discipulado":"#00c97b"};
const USERS=[
 {email:"pastor@distrito.org",code:"1234",name:"Pastor Distrital",role:"Pastor Distrital",church:"Todas"},
 {email:"central@igreja.org",code:"1234",name:"Ancião/Secretária Central",role:"Ancião/Secretária Local",church:"Central"},
 {email:"admin@mopa.org",code:"1234",name:"Administrador da Missão",role:"Administrador da Missão",church:"Todas"}
];
let user=null,records=[],tasks=[],evidences=[],selectedChurch="Todas",selectedYear="2026",selectedMonth="Todos",deferredPrompt=null;
const $=id=>document.getElementById(id),clamp=n=>Math.max(0,Math.min(100,Number(n)||0)),pct=(a,b)=>b?clamp(a/b*100):0;
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),2800)}
function endpoint(){return window.APP_CONFIG.APPS_SCRIPT_URL}
function jsonp(url,action="list",extra={}){return new Promise((resolve,reject)=>{const cb="cb_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script");const timer=setTimeout(()=>{cleanup();reject(new Error("timeout"))},25000);function cleanup(){clearTimeout(timer);s.remove();try{delete window[cb]}catch(e){}}window[cb]=d=>{cleanup();resolve(d)};const u=new URL(url);u.searchParams.set("action",action);u.searchParams.set("callback",cb);u.searchParams.set("_",Date.now());Object.entries(extra).forEach(([k,v])=>u.searchParams.set(k,v));s.src=u;s.onerror=()=>{cleanup();reject(new Error("network"))};document.head.appendChild(s)})}
function normalize(r){return {...r,ano:String(r.ano),meta:Number(r.meta)||0,alcancado:Number(r.alcancado)||0,codigo:r.codigo_requisito||r.codigo}}
function login(){const email=$("loginEmail").value.trim().toLowerCase(),code=$("loginCode").value;user=USERS.find(u=>u.email===email&&u.code===code);if(!user){$("loginMessage").textContent="E-mail ou código inválido. Use os acessos de demonstração descritos no README.";return}localStorage.setItem("sessionUser",JSON.stringify(user));startApp()}
function startApp(){$("loginScreen").classList.add("hidden");$("appRoot").classList.remove("hidden");$("profileName").textContent=user.name;$("profileRole").textContent=user.role;document.querySelectorAll(".admin-only").forEach(e=>e.classList.toggle("hidden",user.role!=="Administrador da Missão"));selectedChurch=user.church==="Todas"?"Todas":user.church;setupFilters();loadData()}
function logout(){localStorage.removeItem("sessionUser");location.reload()}
function setupFilters(){$("churchFilter").innerHTML=["Todas",...CHURCHES].map(c=>`<option>${c}</option>`).join("");$("churchFilter").value=selectedChurch;$("churchFilter").disabled=user&&user.church!=="Todas";$("yearFilter").value=selectedYear}
async function loadData(){ $("refreshIcon").classList.add("spin"); try{const res=await jsonp(endpoint());const rows=Array.isArray(res)?res:res.data;if(!Array.isArray(rows))throw Error();records=rows.map(normalize);localStorage.setItem("v5cache",JSON.stringify(records));$("syncBadge").innerHTML="<i></i>Google Sheets conectado"}catch(e){records=JSON.parse(localStorage.getItem("v5cache")||"[]");$("syncBadge").innerHTML="<i style='background:#ffb800'></i>Modo offline"}finally{$("refreshIcon").classList.remove("spin");renderAll()}}
function filtered(){return records.filter(r=>r.ano===selectedYear&&(selectedChurch==="Todas"||r.igreja===selectedChurch))}
function aggregate(data,key){const m=new Map();data.forEach(r=>{const k=r[key];if(!m.has(k))m.set(k,{key:k,meta:0,alc:0,count:0});const x=m.get(k);x.meta+=r.meta;x.alc+=r.alcancado;x.count++});return [...m.values()].map(x=>({...x,percent:pct(x.alc,x.meta)}))}
function renderAll(){$("contextText").textContent=`${selectedChurch==="Todas"?"Distrito completo":selectedChurch} · ${selectedYear}`;$("lastUpdate").textContent="Última atualização: "+new Date().toLocaleString("pt-BR");renderDashboard();renderPlanner();renderTimeline();renderEvidence();renderAdmin()}
function renderDashboard(){const data=filtered(),total=data.reduce((a,r)=>({m:a.m+r.meta,a:a.a+r.alcancado}),{m:0,a:0}),p=pct(total.a,total.m);$("overallRadial").style.setProperty("--value",p);$("overallPercent").textContent=Math.round(p)+"%";$("overallGoal").textContent=Math.round(total.m);$("overallReached").textContent=Math.round(total.a);const areas=aggregate(data,"area");$("priorityCards").innerHTML=Object.entries(AREAS).map(([area,color])=>{const x=areas.find(v=>v.key===area)||{percent:0,alc:0,meta:0};return `<article class="priority-card" style="--accent:${color}"><strong>${Math.round(x.percent)}%</strong><h3>${area}</h3><p>${Math.round(x.alc)} de ${Math.round(x.meta)} realizados</p><div class="progress"><i style="width:${x.percent}%"></i></div></article>`}).join("");const ranking=aggregate(data,"igreja").sort((a,b)=>b.percent-a.percent);$("rankingList").innerHTML=ranking.map((x,i)=>`<div class="ranking-item"><b>${i+1}</b><div><strong>${x.key}</strong><span>${Math.round(x.alc)} de ${Math.round(x.meta)}</span></div><strong>${Math.round(x.percent)}%</strong></div>`).join("");$("trafficGrid").innerHTML=areas.map(x=>{const c=x.percent>=80?"#00c97b":x.percent>=60?"#ffb800":"#ff0046";return `<div class="traffic-card"><strong><i style="background:${c}"></i>${x.key}</strong><span>${Math.round(x.percent)}% alcançado</span></div>`}).join("");const alerts=data.filter(r=>pct(r.alcancado,r.meta)<60).sort((a,b)=>pct(a.alcancado,a.meta)-pct(b.alcancado,b.meta)).slice(0,8);$("alertsList").innerHTML=alerts.map(r=>`<div class="alert-item"><span>!</span><div><strong>${r.titulo}</strong><span>${r.igreja} · ${r.area}</span></div><strong>${Math.round(pct(r.alcancado,r.meta))}%</strong></div>`).join("");drawEvolution()}
function drawEvolution(){const c=$("evolutionChart"),ctx=c.getContext("2d"),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle="#dbe6ea";ctx.lineWidth=1;for(let i=1;i<5;i++){let y=i*h/5;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-20,y);ctx.stroke()}const vals=[28,35,42,49,58,62,68,71,74,79,83,87].map((v,i)=>clamp(v+(selectedChurch==="Todas"?0:(selectedChurch.length+i)%7)));ctx.strokeStyle="#00bddd";ctx.lineWidth=4;ctx.beginPath();vals.forEach((v,i)=>{const x=45+i*(w-70)/11,y=h-30-v*(h-55)/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle="#102333";ctx.font="12px Inter";["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"].forEach((m,i)=>ctx.fillText(m,35+i*(w-70)/11,h-8))}
function renderPlanner(){if(!tasks.length)tasks=JSON.parse(localStorage.getItem("v5tasks")||"[]");if(!tasks.length){filtered().slice(0,9).forEach((r,i)=>tasks.push({id:Date.now()+i,title:r.titulo,owner:r.responsavel||"Não definido",due:"2026-12-31",status:["Não iniciado","Em andamento","Concluído"][i%3]}))}const statuses=["Não iniciado","Em andamento","Concluído"];$("kanbanBoard").innerHTML=statuses.map(s=>`<section class="kanban-column"><h3>${s}</h3>${tasks.filter(t=>t.status===s).map(t=>`<article class="task-card"><strong>${t.title}</strong><span>${t.owner}</span><span>Prazo: ${t.due||"—"}</span></article>`).join("")}</section>`).join("")}
function renderTimeline(){const items=[...tasks].sort((a,b)=>(a.due||"").localeCompare(b.due||""));$("timelineList").innerHTML=items.map(t=>`<article class="timeline-item"><strong>${t.title}</strong><span>${t.owner} · ${t.status} · ${t.due||"Sem prazo"}</span></article>`).join("")}
function renderEvidence(){const opts=filtered().map(r=>`<option value="${r.id}">${r.igreja} · ${r.titulo}</option>`).join("");$("evidenceCriterion").innerHTML=opts;evidences=JSON.parse(localStorage.getItem("v5evidences")||"[]");$("evidenceGallery").innerHTML=evidences.map(e=>`<article class="evidence-card">${e.preview?`<img src="${e.preview}" alt="">`:""}<div><strong>${e.description}</strong><span>${e.fileName}</span></div></article>`).join("")}
function uploadEvidence(){const file=$("evidenceFile").files[0];if(!file)return toast("Selecione um arquivo.");const reader=new FileReader();reader.onload=()=>{evidences.push({criterion:$("evidenceCriterion").value,description:$("evidenceDescription").value||"Evidência",fileName:file.name,preview:file.type.startsWith("image/")?reader.result:""});localStorage.setItem("v5evidences",JSON.stringify(evidences));renderEvidence();toast("Evidência adicionada localmente. Para envio ao Drive, atualize o Code.gs da V5.")};reader.readAsDataURL(file)}
function renderAdmin(){$("usersTable").innerHTML=`<table style="width:100%;border-collapse:collapse">${USERS.map(u=>`<tr><td style="padding:10px;border-bottom:1px solid #e5edef">${u.name}</td><td>${u.role}</td><td>${u.church}</td><td>${u.email}</td></tr>`).join("")}</table>`}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(name+"View").classList.add("active");document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.view===name));const titles={dashboard:"Dashboard Executivo",planner:"Planner",timeline:"Linha do tempo",evidence:"Evidências",reports:"Relatórios",admin:"Administração"};$("viewTitle").textContent=titles[name]||name;$("sidebar").classList.remove("open")}
function exportCSV(){const rows=filtered(),headers=["igreja","ano","area","titulo","meta","alcancado","plano_acao","responsavel","data_inicial","voto","material"],csv=[headers,...rows.map(r=>headers.map(h=>r[h]??""))].map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download="prioridades-estrategicas.csv";a.click();URL.revokeObjectURL(a.href)}
function shareWhatsApp(){const data=filtered(),t=data.reduce((a,r)=>({m:a.m+r.meta,x:a.x+r.alcancado}),{m:0,x:0}),text=`*Prioridades Estratégicas*\n${selectedChurch==="Todas"?"Distrito Castelo de Sonhos":selectedChurch} — ${selectedYear}\nResultado geral: *${Math.round(pct(t.x,t.m))}%*`;window.open("https://wa.me/?text="+encodeURIComponent(text),"_blank")}
async function sendEmail(){const email=$("reportEmail").value.trim();if(!email)return;const body=new URLSearchParams({action:"sendReport",email,igreja:selectedChurch,ano:selectedYear});await fetch(endpoint(),{method:"POST",mode:"no-cors",body});toast("Solicitação de envio realizada.");$("emailModal").classList.remove("open")}
document.addEventListener("DOMContentLoaded",()=>{const saved=localStorage.getItem("sessionUser");if(saved){user=JSON.parse(saved);startApp()}$("loginButton").onclick=login;$("logoutButton").onclick=logout;document.querySelectorAll(".nav-button").forEach(b=>b.onclick=()=>showView(b.dataset.view));$("churchFilter").onchange=e=>{selectedChurch=e.target.value;renderAll()};$("yearFilter").onchange=e=>{selectedYear=e.target.value;renderAll()};$("monthFilter").onchange=e=>{selectedMonth=e.target.value;renderAll()};$("refreshButton").onclick=loadData;$("mobileMenu").onclick=()=>$("sidebar").classList.toggle("open");$("presentationButton").onclick=()=>document.documentElement.requestFullscreen?.();$("newTaskButton").onclick=()=>$("taskModal").classList.add("open");$("saveTask").onclick=()=>{tasks.push({id:Date.now(),title:$("taskTitle").value,owner:$("taskOwner").value,due:$("taskDue").value,status:$("taskStatus").value});localStorage.setItem("v5tasks",JSON.stringify(tasks));$("taskModal").classList.remove("open");renderPlanner();renderTimeline()};$("uploadEvidence").onclick=uploadEvidence;$("pdfButton").onclick=()=>window.print();$("excelButton").onclick=exportCSV;$("whatsappButton").onclick=shareWhatsApp;$("emailButton").onclick=()=>$("emailModal").classList.add("open");$("sendEmail").onclick=sendEmail;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove("open"));window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installButton").classList.remove("hidden")});$("installButton").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js")})